### ISSUE TITLE
Set command for resources with "/" on their name fails using the SDK (IssueSetCommandByName) 

### ISSUE THREAD

**Issue by idiazcir** [edgexfoundry/go-mod-core-contracts#893]
# 🐞 Bug Report

### Affected Services
SDK - Application service: CommandClient/IssueSetCommandByName

### Is this a regression?

No idea. We are using version 3.1.

### Description and Minimal Reproduction 

Resources that have a forward slash `/` character on the name, like for instace `charge/stop`:

```yaml
---
name: "evse-ctrlr"
model: "EVSECtrlr" 
description: "MQTT communication profile for Circontrol's EVSE"
deviceResources:
- name: charge/stop
    isHidden: true
    properties:
      valueType: "Bool"
      readWrite: "W"
```
When we do a set command using the SDK from an application on the north, as so:

```go
variable := "charge/stop"
res, err := app.Service.CommandClient().IssueSetCommandByName(ctx, "EVSECTRL_1", variable, map[string]string{variable: "true"})
```
It fails to be written and produces and error. It interprets that the name of the device is the first word before the `/` character. In this case, it interprets the name to be `charge` (which is a part of the resource, not the name of the device). See the error on the section below.

**NOTE:**
**This only happens for the Set command from the SDK. The Get using the SDK works fine, and BOTH the Set and Get using the APIs of the device or the core-command directly seems to work too**.

## 🔥 Exception or Error
```txt
invalid request topic: failed to get Device by name charge': request failed, status code: 404, err: {"apiVersion":"v3","message":"fail to query device by name charge'","statusCode":404}
```

## 🌍  Your Environment
**Deployment Environment:** Linux Ubuntu 20.04

**EdgeX Version:** 3.1

**Anything else relevant?**
